### ISSUE TITLE
Fix Travis checks

### ISSUE THREAD

**Issue by anton-khodak** [erasche/argparse2tool#41]
Fix and enhance

**Comment by hmenager** [comment]
do you want me to take care of it @anton-khodak ?

**Comment by anton-khodak** [comment]
@hmenager if you have time and desire, you are welcome to do so :) but actually I created this for myself

**Comment by hmenager** [comment]
ok, my bad, build still fails, multiple points of failure (style + others)

**Comment by anton-khodak** [comment]
@hmenager don't worry about that, I will deal with these issues in bulk somewhere on the next week (promise!)

**Comment by erasche** [comment]
Partially failure is due to me adding in a new datastructure which affected galaxy xml. Will look into this week.

**Comment by anton-khodak** [comment]
Fixed https://github.com/erasche/argparse2tool/commit/02b3b12c0cb242dfa75bb51db73d2f13b4dc1ad3, https://github.com/erasche/argparse2tool/commit/d456a89073cfed40d133337edbc45ef0ded4935a
