### ISSUE TITLE
Argparse2galaxy select field

### ISSUE THREAD

**Issue by anton-khodak** [erasche/argparse2tool#46]
The last issue that blocks successful travis checks is the resolving of default values in select fields.

`example.py`
```
...
parser.add_argument('--mode', choices=['rock', 'paper', 'scissors'], default='scissors')
...
```
In the example the default value is placed on the first place in the list of choices
`example.xml`
```
    <param argument="--mode" label="Author did not provide help for this parameter... " name="mode" optional="true" type="select">
      <option selected="true" value="scissors">scissors</option>
      <option value="paper">paper</option>
      <option value="rock">rock</option>
    </param>
```

The current version of argparse2tool resolves the default value in the order it appeared in argparse choices:
```
    <param argument="--mode" label="Author did not provide help for this parameter... " name="mode" optional="true" type="select">
      <option value="paper">paper</option>
      <option value="rock">rock</option>
      <option selected="true" value="scissors">scissors</option>
    </param>
```

If the behavior of the current version is correct than we should simple update `example.xml`.

**Comment by mr-c** [comment]
The latter is fine, yep!

**Comment by anton-khodak** [comment]
Fixed by https://github.com/erasche/argparse2tool/commit/4740e40b6b7973266b6977c4e381ce0c3bf6d38e

**Comment by erasche** [comment]
looks like a bug that they aren't sorted identically to the input. I'll file that for myself.
