### ISSUE TITLE
PR policy?

### ISSUE THREAD

**Issue by mr-c** [erasche/argparse2tool#52]
I think we may be at the point that a PR should be created always, no direct pushing to the main branch unless absolutely necessary.

@erasche @anton-khodak What are your thoughts?

**Comment by anton-khodak** [comment]
Yes, it is the safest way, so I'm for it.

**Comment by bgruening** [comment]
Pushing directly to the master branch is never good! :+1:

**Comment by erasche** [comment]
![utvalg_001](https://cloud.githubusercontent.com/assets/458683/25079000/f1cc3a88-2327-11e7-9c76-331ec9e0ec94.png)

**Comment by erasche** [comment]
On second thought, this doesn't prevent pushing at all, just prevents force pushing. But yes, in favour of PRs only.

**Comment by mr-c** [comment]
I'm happy to do PR reviews for CWL or simple fixes, if you want to require them

**Comment by erasche** [comment]
Given how barely related the two sides are other than in idea, please, feel free to manage the cwl however fits y'all's style. As long as we're not breaking each other's stuff I think we're fine :)
